# This is a workflow triggered by PR or triggered manually
# Runs quick performance tests and reports the comparison against HEAD
# Test should take less than 10 minutes to run on current self-hosted devices
name: "Validate Build"

# Controls when the action will run.
on:
  - push

# Env variables
env:
  SG_COMMIT: 2ab01ac
  GITHUB_CONTEXT: ${{ toJson(github) }}

jobs:
  Validate_Build:
    name: Validate Build
    runs-on: ubuntu-latest
    steps:
      - name : Checkout
        uses: actions/checkout@v3

      - run: echo "$GITHUB_CONTEXT"

      - run: |
          # Build
          ./build.sh

        name: Run wasm-score benchmarks
      - run: |
          # Run
          docker run wasmscore /bin/bash wasmscore.sh -t quickrun_all
